# embed_resource.cmake - Convert a binary file to a C header with byte array
# Usage: cmake -DINPUT_FILE=... -DOUTPUT_FILE=... -DVAR_NAME=... -P embed_resource.cmake

file(READ "${INPUT_FILE}" content HEX)

# Convert hex pairs to 0xNN, format
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex_content "${content}")

# Get file size
file(SIZE "${INPUT_FILE}" file_size)

# Write the header
file(WRITE "${OUTPUT_FILE}"
"// Auto-generated by embed_resource.cmake - do not edit\n"
"#pragma once\n"
"#include <cstddef>\n\n"
"static const unsigned char ${VAR_NAME}[] = {\n"
"${hex_content}\n"
"};\n\n"
"static const size_t ${VAR_NAME}_size = ${file_size};\n"
)
